FROM public.ecr.aws/lambda/python

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum install -y chromium chromedriver ipa-gothic-fonts ipa-mincho-fonts ipa-pgothic-fonts ipa-pmincho-fonts

COPY requirements.txt .
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY core.py ${LAMBDA_TASK_ROOT}
COPY lambda_function.py.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.handler"]
