FROM public.ecr.aws/lambda/python:3.12

COPY fedora.repo /etc/yum.repos.d/fedora.repo

RUN dnf install -y --enablerepo=fedora chromium chromedriver ipa-gothic-fonts ipa-mincho-fonts ipa-pgothic-fonts ipa-pmincho-fonts \
  && dnf clean all

COPY requirements.txt .
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY core.py ${LAMBDA_TASK_ROOT}
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.handler"]
