name: Build docker image for Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::258472941923:role/GitHubActionsDeployRole
  REPOSITORY: pdf-generator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
      - uses: actions/checkout@v4
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile-lambda
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:latest
          cache-to: type=inline
